// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string query = 1;</code>
   * @return Whether the query field is set.
   */
  boolean hasQuery();
  /**
   * <code>optional string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>optional string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>optional string username = 2;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>optional string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional int32 userid = 3;</code>
   * @return Whether the userid field is set.
   */
  boolean hasUserid();
  /**
   * <code>optional int32 userid = 3;</code>
   * @return The userid.
   */
  int getUserid();
}
